### ISSUE TITLE
Remove unused variables and use types that are more fun to read

### ISSUE THREAD

**Issue by Gunzinger** [KorbinianOrt/ATmega328_Funkuhr#2]
https://github.com/KorbinianOrt/ATmega328_Funkuhr/blob/39c3e0e285b2678c7015ceae8c85fd9db2b419ff/ATmega328_Funkuhr.ino#L75

contains an unused variable.

Also it would be helpful to use the bool type for flags in your code as they are naturally cool and the word bool is more fun to read than int.

You can be nice to the compiler and show it some trust by removing the volatile declaration of most variables.
This would probably help the compilers mood, especially if it has a bad day or is somehow feeling down.

Thanks in advance and have a nice day,
Gunzinger.

**Comment by KorbinianOrt** [comment]
ok :)

**Comment by KorbinianOrt** [comment]
> use the bool type for flags in your code as they are naturally cool and the word bool is more fun to read than int.

F A C T S. 😎
That will be in my next commit.
